repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: debug-statements

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
    -   id: ruff-check
        args: ["--fix"]
        files: ^logeverything/
    -   id: ruff-format
        files: ^logeverything/
    -   id: ruff-check
        name: ruff-check-dashboard
        args: ["--fix"]
        files: ^logeverything-dashboard/
    -   id: ruff-format
        name: ruff-format-dashboard
        files: ^logeverything-dashboard/

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-PyYAML, types-colorama, types-requests]
        files: ^logeverything/

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        files: ^logeverything/
        additional_dependencies: [pbr]
